[package]
name = "restapi"
version = "0.1.0"
edition = "2021" # Changed from 2024 for compatibility with rust:1.78

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15" # For .env file support
