apiVersion: v1
kind: Service
metadata:
  name: restapi-service # Name of the Service
spec:
  type: NodePort # Exposes the Service on each Node's IP at a static port (the NodePort)
  selector:
    app: restapi # Selects Pods with the label 'app=restapi' to route traffic to
  ports:
    - protocol: TCP
      port: 3000 # Port the Service listens on within the cluster
      targetPort: 3000 # Port on the Pods to forward traffic to
      # nodePort: 30080 # Optional: specify a static NodePort (if omitted, K8s assigns one)
